CREATE OR REPLACE PACKAGE XXAV_PICKSLIP_LIST_PKG
AS
   P_MOVE_ORDER_LOW    NUMBER;
   P_MOVE_ORDER_HIGH   NUMBER;

   FUNCTION UPDATE_MOVE_ORDER (P_MOVE_ORDER_LOW    IN NUMBER DEFAULT NULL,
                               P_MOVE_ORDER_HIGH   IN NUMBER DEFAULT NULL)
      RETURN BOOLEAN;
END XXAV_PICKSLIP_LIST_PKG;